### PR TITLE
update i18n gem to 1.4.0

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ehelms** [comment]
Looks like we need to drop line 72

**Comment by mmoll** [comment]
:green_heart:

**Comment by tbrisker** [comment]
what's the status here @ehelms @mmoll ?

**Comment by mmoll** [comment]
IMHO this is ready.

**Comment by mmoll** [comment]
actually... let me udpate that to 1.4.0 first...

**Comment by mmoll** [comment]
done :green_heart:

**Comment by tbrisker** [comment]
ping @ehelms or @ekohl - would be good to get this updated for 1.21

**Review by ehelms — APPROVED** [review]

**Comment by mmoll** [comment]
@ehelms https://ci.theforeman.org/job/tfm-ror52-rpm-pipeline/107/ failed I guess that means it's not in the staging repo?

**Comment by ehelms** [comment]
Correct -- but I had a note to fix the pipeline. I am working on that. You can see it there now:

http://yum.theforeman.org/rails/foreman-nightly/el7/x86_64/

With these updates to the job:

https://github.com/theforeman/foreman-infra/pull/899

**Pull request merged**
