### PR TITLE
update uglifier to 4.1.6

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
seems like some annex thingy is wrong and setup_sources.sh doesn't work for me

**Comment by ehelms** [comment]
Goodie, a real test case for updating the job to Obal! I'll be making changes to the job and hoping to use this a test case.

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
Thanks for the patience. This successfully passed the new use of Obal. Now to merge it and test release....

**Pull request merged**
