### PR TITLE
Add sinatra 2.0.3

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Review by zjhuntin — APPROVED** [review]
APK

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
```
    package: tfm-ror52-rubygem-sinatra-2.0.3-1.el7.noarch from downloaded_rpms
      unresolved deps:
         tfm-ror52-rubygem(tilt)
         tfm-ror52-rubygem(rack-protection)
         tfm-ror52-rubygem(mustermann)
```

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
