### PR TITLE
Add coffee-script 2.4.1

### PR DESCRIPTION
**Pull request by xprazak2**
Needed by coffee-rails
Needs coffee-script-source

### CODE REVIEW

**Comment by xprazak2** [comment]
[test]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
@xprazak2 Thanks for tackling adding this! So you know in the future, you can re-test by doing what I did in the previous comment. Unlike what you are used to, this is using a slightly different trigger so you have to specify the name of the job.

**Comment by xprazak2** [comment]
Failing on missing coffee-script-source, I do not see it among [packages](https://copr-fe.cloud.fedoraproject.org/coprs/g/theforeman/tfm-ror51/packages/)

@ehelms, is copr supposed to pick up when new packages are merged and build them or am I 
supposed to run `ansible-playbook release_package.yml -l <package_name>` manually?

**Comment by ehelms** [comment]
There's a job that handles that and appears to be in error due to job
configuration I must have messed up.

http://ci.theforeman.org/job/tfm-ror51-release/50/console

**Comment by ehelms** [comment]
If you look at (
https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/tfmROR51.groovy)
the entire find packages step is not needed and can be removed to fix it.

**Comment by xprazak2** [comment]
Thanks for hints, I opened the [find packages](https://github.com/theforeman/foreman-infra/pull/403) step

**Comment by ehelms** [comment]
Thanks! Merged, will be about 30 minutes for change to propagate and then
you can run the release job again.

**Comment by xprazak2** [comment]
[test copr]

**Pull request merged**
