### PR TITLE
Add uglifier 4.1.18

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by evgeni** [comment]
```
    package: tfm-ror52-rubygem-uglifier-4.1.18-1.el7.noarch from downloaded_rpms
      unresolved deps:
         tfm-ror52-rubygem(execjs)
```

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
`execjs` is not in http://koji.katello.org/releases/yum/tfm-ror52/el7/x86_64/ -- isn't that automatically deployed from the built packages here?

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
@evgeni Updated

**Review by komidore64 — APPROVED** [review]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
