### PR TITLE
Switch to using Obal

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Requires -- https://github.com/theforeman/foreman-infra/pull/488

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ekohl** [comment]
Does this replace https://github.com/theforeman/tfm-ror51-packaging/pull/42?

**Pull request merged**
