### PR TITLE
Arel 9.0.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Review by pcreech — APPROVED** [review]

**Comment by pcreech** [comment]
ACK

**Review by ekohl — APPROVED** [review]

**Pull request merged**
