### PR TITLE
Bump releases to rebuild against newest tfm-ror51

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ekohl** [comment]
Don't we need a changelog entry for every spec file?

**Comment by ehelms** [comment]
@ekohl Updated by using -- https://github.com/theforeman/obal/pull/85

**Comment by ekohl** [comment]
tfm-ror51-rubygem-actionpack failed with `BUILDSTDERR: warning: Could not canonicalize hostname: 750b14a7bb454c4482cff47ca5975e07`. Not sure that's related to our env.

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
[test copr]

**Comment by ehelms** [comment]
Does not look like this can finish in the time needed by Jenkins given Copr varying loads. Since this is a simple release bump, any objection to merging?

**Comment by evgeni** [comment]
no objection

**Pull request merged**
